services:
  backend:
    build: ./back-end
    ports:
      - "5000:3000"

  frontend:
    build: ./front-end
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3000